export default {
    white: "white",
    black: "black",
    blue: "blue",
    green: "green",
    grey: "grey",
    yellow: "yellow",
    pink: "pink",
    purple: "purple",
    cyan: "cyan",
    primary: "#00286B",
    secondary: "#F5F9FF", 
    red : "red",
    mediumGrey: '#6e6969',
    lighGrey: '#f8f4f4',
    danger: '#ff5252',
    dark: "#0c0c0c",
    button: "#1A202E",
    light: "#788190",
}